server:
  port: 8081

url:
  weatherUrl: https://api.openweathermap.org/data/2.5/weather?q=

key:
  keyForApi: 58f9b3be23fbf4bff065c9fa498cbe75
spring:
  data:
    mongodb:
      database: shedLock
      uri: mongodb+srv://admin:<admin>@weather-abfut.mongodb.net/test?retryWrites=true&w=majority