spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/weatherapp
    username: weatherapp
    password: lucratorcomputer
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      database: shedLock
      uri: mongodb+srv://admin:admin@weather-abfut.mongodb.net/test?retryWrites=true&w=majority
      admin: admin
      password: admin
  profiles:
    cloud
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.mysqldialect