spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/weatherapp
    username: weatherapp
    password: lucratorcomputer
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    cloud
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.mysqldialect